### ISSUE TITLE
迁移实验 & 学生模型

### ISSUE THREAD

**Issue by JinYu1998** [sunshangquan/logit-standardardization-KD#2]
1. 请问是否考虑过将蒸馏后的模型从CIFAR-100迁移到STL-10数据上?
2. 请问是否可以提供学生模型?

**Comment by sunshangquan** [comment]
1. 我们可能会在之后尝试一下
2. 需要哪个学生网络呢？全部上传的话太多了，所有训练log都提供了，ViT的学生网络也提供了

**Comment by JinYu1998** [comment]
> 1. 我们可能会在之后尝试一下
> 2. 需要哪个学生网络呢？全部上传的话太多了，所有训练log都提供了，ViT的学生网络也提供了

1. 我们在实验中注意到, 部分蒸馏算法蒸馏出的学生模型在迁移实验上的效果很差, 期待您这篇工作在迁移实验上的表现.
2. Table-2中, KD+Ours 中的 ResNet32*4蒸馏ResNet8*4, ResNet56蒸馏ResNet20,  只需要提供学生网络的Best Model就可以了, 非常感谢.

**Comment by sunshangquan** [comment]
1. 如果可以的话，您可以尝试一下，我们可能需要等到下半年之后才有计划
2. 我找了两个实验的best学生，两个网络都在 https://www.dropbox.com/scl/fo/hqbvmfdon7yha7ydvmof1/h?rlkey=c3ftsqkpflwv4oi3e1khf36m6&dl=0 , acc分别是76.86和71.53。
谢谢您的关注

**Comment by JinYu1998** [comment]
> 1. 如果可以的话，您可以尝试一下，我们可能需要等到下半年之后才有计划
> 2. 我找了两个实验的best学生，两个网络都在 https://www.dropbox.com/scl/fo/hqbvmfdon7yha7ydvmof1/h?rlkey=c3ftsqkpflwv4oi3e1khf36m6&dl=0 , acc分别是76.86和71.53。
>    谢谢您的关注

好的, 非常感谢. 
稍后我将会自己跑一下这个实验. 

感谢您的回复, 这篇工作非常棒!

**Comment by sunshangquan** [comment]
觉得有帮助的话可以给个star支持一下~谢谢啦
