### ISSUE TITLE
tiny-transformer

### ISSUE THREAD

**Issue by lyxiang-casia** [sunshangquan/logit-standardardization-KD#21]
我在复现您有关ViT的实验时发现，除了DeiT模型以外，其他模型并不会返回logits，因而无法进行基于logits的蒸馏，可以请您解答一下吗

**Comment by sunshangquan** [comment]
您好，logit的返回都是在这几行[PIT](https://github.com/sunshangquan/logit-standardization-KD/blob/eb569ac3783f2eed16fbc2b021101175af4fb2f2/tiny-transformers/pycls/models/transformers/pit.py#L171), [PVT](https://github.com/sunshangquan/logit-standardization-KD/blob/eb569ac3783f2eed16fbc2b021101175af4fb2f2/tiny-transformers/pycls/models/transformers/pvt.py#L236), [T2T-ViT](https://github.com/sunshangquan/logit-standardization-KD/blob/eb569ac3783f2eed16fbc2b021101175af4fb2f2/tiny-transformers/pycls/models/transformers/t2t_vit.py#L237)，经过了self.head的就是logit了，其实deit也是这样的，请见[deit](https://github.com/sunshangquan/logit-standardization-KD/blob/eb569ac3783f2eed16fbc2b021101175af4fb2f2/tiny-transformers/pycls/models/transformers/deit.py#L90)

**Comment by lyxiang-casia** [comment]
十分感谢您的回复
