### ISSUE TITLE
MobileNet

### ISSUE THREAD

**Issue by lyxiang-casia** [sunshangquan/logit-standardardization-KD#22]
在imagenet实验中给出的是MobileNetV2，但是结果中是MobileNetV1。我查看了您这里的V2的结构和DKD工作中的V1结构相同，请问您这里的V2是命名有问题还是别的什么问题呢？

**Comment by sunshangquan** [comment]
Hi @lyxiang-casia , 这应该是一个typo，请见[mdistiller/issues/18](https://github.com/megvii-research/mdistiller/issues/18), [Multi-Level-Logit-Distillation/issues/8](https://github.com/Jin-Ying/Multi-Level-Logit-Distillation/issues/8). 所以应该是MobileNetV1。

**Comment by lyxiang-casia** [comment]
好的，谢谢
