### ISSUE TITLE
best or last?

### ISSUE THREAD

**Issue by RenshengJi** [sunshangquan/logit-standardardization-KD#23]
It is a good work, but I would like to ask whether you used the best epoch or the last epoch in your result, because it was not mentioned in the paper. At the same time, which one do you think is reasonable to choose? Why?

**Comment by sunshangquan** [comment]
Hi @RenshengJi , thanks for the attention. The practice of reporting the best epoch is adopted from the previous works of [DKD](https://github.com/megvii-research/mdistiller) and [CTKD](https://github.com/zhengli97/CTKD/issues/14).

**Comment by RenshengJi** [comment]
thanks.
