### ISSUE TITLE
实现层面

### ISSUE THREAD

**Issue by zzeoZheng** [sunshangquan/logit-standardardization-KD#3]
作者你好，请问在实现层面是否仅有对学生和老师的logit做Normalize操作呢？是否还有其它我没发现的地方需要处理？正在学习您的工作，希望可以得到回复。

**Comment by sunshangquan** [comment]
实验方面为了公平对比，对训练过程都沿用了CTKD、DKD和MLKD各自的训练设置，实现的时候的核心代码是
```
mean = logit.mean(dim=-1, keepdims=True)
stdv = logit.std(dim=-1, keepdims=True)
logit = (logit - mean) / (1e-7 + stdv)
```
1e-7是为了计算的时候数值稳定，防止stdv为0的情况，除此之外需要注意的是基础温度和KD损失函数的权重，希望我的回复可以帮到你

**Comment by zzeoZheng** [comment]
好的，感谢回复。另外还有两个问题请教：
1. 我在论文中看到前面的论证了教师和学生的温度不一定是一样的，甚至共享温度是不太好的，可是在实现层面好像并没有对温度进行调整？是不是Logit Standardization就可以达到上述效果。
2. 对于MLKD的实验，我看原文是使用了一些不符合非常规操作例如一些数据增强和epoch设置，请问你都是按照他的实验设置进行实验的吗？
期待您的回复！

**Comment by sunshangquan** [comment]
1. Logit Standardization是减去logit均值后除以(std*基础温度)，而为了代码层面的尽量少的变动，基础温度（base temperature）是利用config文件里面的CFG.KD.LOSS.KD_WEIGHT调节的
2. 我们注意到了MLKD才用了更长的epoch和更多数据增强，在论文里有提到（“ the epoch number is 240, except for MLKD being 480”），但是我们的实验是为了验证Logit Standardization能否增益现有logit-based蒸馏算法的效果，所以采用了与其一致的训练过程；其他蒸馏算法如DKD、KD、CTKD还是用的它们各自的原始设置，和MLKD的变化无关
谢谢您的关注！希望我的回复可以帮到您

**Comment by zzeoZheng** [comment]
理解了，非常感谢您的回复！
