### ISSUE TITLE
交叉熵损失的作用是什么

### ISSUE THREAD

**Issue by wuyu1212** [sunshangquan/logit-standardardization-KD#4]
1. 您在算法部分出现Lce，对于它的作用我在文章中并没有找寻到（可能是我没有找到，如果是这样非常抱歉）
2. 我现在在进行互相知识蒸馏，没有使用Lce，仅仅只使用了预处理部分代码可是效果并不理想
希望您抽空解答一下我的疑问，非常感谢

**Comment by sunshangquan** [comment]
1. 交叉熵并没有在蒸馏的部分用到，而是在算法里面的常规训练部分用到，也就是学生网络与标签y_n之间的损失函数
2. 我们在ICCV rebuttal阶段在互蒸馏上尝试过，增益也不显著，原因可能是方法优势的条件是学生、教师之间的logit存在capacity gap，动机也是为此，而互蒸馏和自蒸馏的情况下，这种gap不存在
希望我的回复能帮到您

**Comment by wuyu1212** [comment]
知道了，谢谢答疑
