### ISSUE TITLE
怎么迁移到多标签分类任务上？

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [sunshangquan/logit-standardardization-KD#5]

**Comment by sunshangquan** [comment]
Hi, I read a paper about KD for multi-label classification [https://arxiv.org/pdf/1809.05884.pdf], and from its Eq. 1, multi-label classification is to set an indicator function parameterized with a threshold for the output logit to decide which classes to predict. If so, you could directly apply our method onto the task and use Eq. 1 during test time.

Hope my reply could help you.

**Comment by zimenglan-sysu-512** [comment]
thanks, i will try it.
