### ISSUE TITLE
想问一下logit具体的计算方式

### ISSUE THREAD

**Issue by wangxxkk** [sunshangquan/logit-standardardization-KD#7]
作者您好，以cifar100为例，想问一下您具体是怎么计算每一类的logit的，是将所有的测试集输入到模型中，然后将所有输出的logit求和，最终除以测试集大小吗。

**Comment by sunshangquan** [comment]
我们对一个batch内的logit（尺寸为BxK），求K维度的标准差（尺寸为Bx1）和均值（尺寸为Bx1），然后做标准化，具体可以查看论文和代码

**Comment by wangxxkk** [comment]
感谢您，但是我具体想问的是，例如论文中的图3的第一行，每一类的logit的值和标准差是如何求出来的呢

**Comment by sunshangquan** [comment]
你可以查看刚上传的https://github.com/sunshangquan/logit-standardization-KD/blob/master/tools/visualizations/correlation.ipynb （图3和图5）以及https://github.com/sunshangquan/logit-standardization-KD/blob/master/tools/visualizations/tsne.ipynb （图4），里面的模型文件需要替换成您自己的，我预计明后上传一下里面用到的模型weight

图3的第一行是只展示了一个sample（即B=1），所以直接求当前sample的mean和std就好

**Comment by wangxxkk** [comment]
谢谢！
