### ISSUE TITLE
Missing configuration to reproduce "KD + Ours" result of ResNet-18 student with ResNet-34 teacher

### ISSUE THREAD

**Issue by yoshitomo-matsubara** [sunshangquan/logit-standardardization-KD#9]
Hi @sunshangquan ,

Congratulations for the accepted paper!
I wanted to reproduce the ImageNet result for ResNet-18 student with ResNet-34 teacher

README.md says 
```shell
python tools/train.py --cfg configs/imagenet/r34_r18/kd_ours.yaml
```
but there are no file names ending with _ours.yaml in `configs/imagenet/r34_r18/`

Could you share the configuration file to reproduce the result?

**Comment by sunshangquan** [comment]
Hi, @yoshitomo-matsubara. I am sorry for the confusion. The script you mentioned in README is for another version and the correct one is
```
# KD
python tools/train.py --cfg configs/imagenet/r34_r18/kd.yaml
# KD+Ours
python tools/train.py --cfg configs/imagenet/r34_r18/kd.yaml --logit-stand --base-temp 2 --kd-weight 9 
```
I will update the README today. Hope the reply could help.

**Comment by yoshitomo-matsubara** [comment]
Thank you @sunshangquan

I will give it a try with the hyperparameters

**Comment by yoshitomo-matsubara** [comment]
Hi @sunshangquan 
"KD + Ours" method gave me 71.23% for ResNet-18.
Is the result reasonable?

**Comment by sunshangquan** [comment]
Hi @yoshitomo-matsubara 
It is within the reasonable range as the randomness exists. You could also try ```--base-temp 3``` or ```--kd-weight 3/6/9/12/15```.
I will upload my log files later. Hope this help you.

**Comment by yoshitomo-matsubara** [comment]
Where can I find the log files for ResNet-18 with ImageNer?
I tried two more configs: 1) temperature=3 and 2) beta=3, but still the initial result (71.23%) is best.

**Comment by sunshangquan** [comment]
Hi, @yoshitomo-matsubara . I am sorry for the late uploading of the log file. I will upload it within 2 weeks as I am busy in another work recently.

**Comment by sunshangquan** [comment]
Hi, @yoshitomo-matsubara , I have retrained a version with KD_Weight=9.0, CE_weight=1.0, BASE_TEMP=2. The log file is at [log](https://github.com/sunshangquan/logit-standardization-KD/blob/master/logs/imagenet/r34_r18_kd_ours.txt) and pre-trained model is at [model](https://github.com/sunshangquan/logit-standardization-KD/releases/tag/imagenet_model). The best acc is 71.45. For this experimental setting, KD_Weight within 9 to 12 would be better than other ranges. Hope this could help you.

**Comment by yoshitomo-matsubara** [comment]
Thank you @sunshangquan !
